[package]
name = "gobble-solana"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-account-info = "3.0"
solana-instructions-sysvar = "3.0"
solana-msg = "3.0"
solana-program-entrypoint = "3.0"
solana-program-error = "3.0"
solana-pubkey = "4"

[features]
no-entrypoint = []
