#!/usr/bin/env bash
set -euo pipefail

# The bs58-encoded transactions below were generated by:
#   cargo run --example txn -p gobble-lib
# Each invokes the router program with a different target (gobble, amm, gobble-solana).
# Signatures are dummies — the CLI only needs the message structure for simulation.

RPC="${RPC_URL:-https://api.mainnet-beta.solana.com}"

cargo build -p gobble

echo "=== Test 1: Router -> Gobble (TRUE POSITIVE) ==="
echo "    Expected: forbidden access DETECTED"
echo ""
./target/debug/gobble \
  '6PEJ2i3bV7C36FdAFUcP4ojTC99w5RUfso2xZwP2jteCAmoWkRxwC8VrPGgPLk2fAB4U2jU7VdqnTocFXzXbq52PqQVYm62DR39NaehuX8SJPWPsdpZUh7j6wLNxAqn2jsRfUiAAHFGTtHnMsGmzzAYHbQYwJfHzk5TCRBLpK3CYnZjbj7y8NmTN8VwmybddwAV6U8Hi4fWNjJjxHHfZxeSZsdQVN1GgTVSV6Rub5VddgdQf2ynbmPeajpBLZBRy8wxTNjT46uqyEt61YNKx62KYiRrkPSStYi7kFtmbCMMeCuWDgFyXUU78crH17d1XjGtSgTSMuTZKoEP4zWXGJj' \
  -f 8-16 \
  --rpc-url "$RPC" \
  || true

echo ""
echo "=== Test 2: Router -> AMM (TRUE NEGATIVE) ==="
echo "    Expected: forbidden access NOT detected"
echo ""
./target/debug/gobble \
  '6PEJ2i3bV7C36FdAFUcP4ojTC99w5RUfso2xZwP2jteCAmoWkRxwC8VrPGgPLk2fAB4U2jU7VdqnTocFXzXbq52PqQVYm62DR39NaehuX8SJPWPsdpZUh7j6wLNxAqn2jsRfUiAAHFGTtHnMsGmzzAYHbQYwJfHzk5TCRBLpK3CYnZjbj7y8NmTN8VwmybddwAV6U8Hi4fWNjJjxHHfZxeSZsdQVN1GgRCQf8JiVEGgcTygisdaMxmcFUiBTAkFAjWKK7PpRKZ6AGRxs6g4mdrQhjArNwszqDntYGEumHU5qVjeRB6pzWMMaXgHBcykqmbUL92R2ZpKA5UGDhbokrB' \
  -f 8-16 \
  --rpc-url "$RPC" \
  || true

echo ""
echo "=== Test 3: Router -> GobbleSolana (FALSE POSITIVE) ==="
echo "    Expected: forbidden access DETECTED (false positive from deserialization)"
echo ""
./target/debug/gobble \
  '6PEJ2i3bV7C36FdAFUcP4ojTC99w5RUfso2xZwP2jteCAmoWkRxwC8VrPGgPLk2fAB4U2jU7VdqnTocFXzXbq52PqQVYm62DR39NaehuX8SJPWPsdpZUh7j6wLNxAqn2jsRfUiAAHFGTtHnMsGmzzAYHbQYwJfHzk5TCRBLpK3CYnZjbj7y8NmTN8VwmybddwAV6U8Hi4fWNjJjxHHfZxeSZsdQVN1GgTVSV6f6ZjU4mK9xVE7REKtofaoDW9dmY5LW4rBdRSnAXzmEA8TVEBxora1gu9qqxzYMiUzA7LKyGHJRzzq81VMVKxhLHkwVjDqiNZThs8uzgFqgmYXdD9Z' \
  -f 8-16 \
  --rpc-url "$RPC" \
  || true
